In [44]:
import numpy as np
from scipy import linalg

# Scipy Modülününden Lineer Cebir

4x4'lük Matris oluşturalım.

In [2]:
Matris=np.array([[23,24,12,11],[9,5,15,16],[10,7,27,31],[33,21,34,24]])

Matrisi yazıralım.


In [3]:
Matris

array([[23, 24, 12, 11],
       [ 9,  5, 15, 16],
       [10,  7, 27, 31],
       [33, 21, 34, 24]])

Matirisin Tersini alalım.

In [4]:
Matris_ters=linalg.inv(Matris)

Matirisin Terisini yazdıralım.

In [5]:
Matris_ters

array([[-0.00383172,  0.59172662, -0.26736003, -0.04738818],
       [ 0.05669378, -0.46942446,  0.20073506,  0.0276822 ],
       [-0.0600563 , -0.58273381,  0.2177041 ,  0.13481389],
       [ 0.04074132,  0.42266187, -0.11643728, -0.10838286]])

Matrisin kendisi ile Matrisin Tersinin çarpımıdır.

In [6]:
Matris.dot(linalg.inv(Matris))

array([[ 1.00000000e+00, -8.88178420e-16,  1.33226763e-15,
         0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00,  4.44089210e-16,
         2.22044605e-16],
       [-4.44089210e-16, -1.77635684e-15,  1.00000000e+00,
         0.00000000e+00],
       [-4.44089210e-16, -2.66453526e-15,  2.66453526e-15,
         1.00000000e+00]])

In [7]:
Matris.dot(Matris_ters)

array([[ 1.00000000e+00, -8.88178420e-16,  1.33226763e-15,
         0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00,  4.44089210e-16,
         2.22044605e-16],
       [-4.44089210e-16, -1.77635684e-15,  1.00000000e+00,
         0.00000000e+00],
       [-4.44089210e-16, -2.66453526e-15,  2.66453526e-15,
         1.00000000e+00]])

Matrisin kendisi ile çarpımı.

In [8]:
Matris.dot(Matris)

array([[1228,  987, 1334, 1273],
       [ 930,  682, 1132, 1028],
       [1586, 1115, 2008, 1803],
       [2080, 1639, 2445, 2329]])

Matrisin 0 ile 4 ile ve sonrasında 1.2 çarpımı

In [9]:
Matris.dot(0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
Matris.dot(4)

array([[ 92,  96,  48,  44],
       [ 36,  20,  60,  64],
       [ 40,  28, 108, 124],
       [132,  84, 136,  96]])

In [11]:
Matris.dot(1.2)

array([[27.6, 28.8, 14.4, 13.2],
       [10.8,  6. , 18. , 19.2],
       [12. ,  8.4, 32.4, 37.2],
       [39.6, 25.2, 40.8, 28.8]])

Matrisin determinatını bulup yazdıralım.

In [12]:
Matrisin_Determinatı=linalg.det(Matris)
Matrisin_Determinatı

12788.000000000007

In [13]:
Matrisin_Determinatı_1=linalg.det(Matris,overwrite_a=True,)
Matrisin_Determinatı_1

12788.000000000007

In [14]:
Matrisin_Determinatı_2=linalg.det(Matris,overwrite_a=True,check_finite=False)
Matrisin_Determinatı_2

12788.000000000007

In [15]:
Matrisin_Determinatı_2=linalg.det(Matris,overwrite_a=False,check_finite=False)
Matrisin_Determinatı_2

12788.000000000007

Numpy modülünden 4x4 'lük birim matris oluşturduk.

In [16]:
Birim_Matris=np.eye(4)
Birim_Matris

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Matrisi çözümlemek gibi düşünülebilir.

In [17]:
linalg.solve(Matris,Birim_Matris)

array([[-0.00383172,  0.59172662, -0.26736003, -0.04738818],
       [ 0.05669378, -0.46942446,  0.20073506,  0.0276822 ],
       [-0.0600563 , -0.58273381,  0.2177041 ,  0.13481389],
       [ 0.04074132,  0.42266187, -0.11643728, -0.10838286]])

Bu işlemi yapınca değerlerin 2 ile çarpıldığı görülüyor.

In [18]:
linalg.solve(Matris,Birim_Matris.dot(2))

array([[-0.00766343,  1.18345324, -0.53472005, -0.09477635],
       [ 0.11338755, -0.93884892,  0.40147013,  0.0553644 ],
       [-0.12011261, -1.16546763,  0.4354082 ,  0.26962778],
       [ 0.08148264,  0.84532374, -0.23287457, -0.21676572]])

Lower true dediğimde pek bişey değişmedi.

In [19]:
linalg.solve(Matris,Birim_Matris,lower=True)

array([[-0.00383172,  0.59172662, -0.26736003, -0.04738818],
       [ 0.05669378, -0.46942446,  0.20073506,  0.0276822 ],
       [-0.0600563 , -0.58273381,  0.2177041 ,  0.13481389],
       [ 0.04074132,  0.42266187, -0.11643728, -0.10838286]])

Genel Matris anlamındaki 'gen' parametresini kullandım ve yine bişeyler değişmedi default olarak zaten bu geliyordu.

In [20]:
linalg.solve(Matris,Birim_Matris,lower=True,assume_a="gen")

array([[-0.00383172,  0.59172662, -0.26736003, -0.04738818],
       [ 0.05669378, -0.46942446,  0.20073506,  0.0276822 ],
       [-0.0600563 , -0.58273381,  0.2177041 ,  0.13481389],
       [ 0.04074132,  0.42266187, -0.11643728, -0.10838286]])

Transposed=True yaptığımda ortaya çıkan matrisin transpozunu sunuyor.

In [21]:
linalg.solve(Matris,Birim_Matris,lower=True,assume_a="gen",transposed=True)

array([[-0.00383172,  0.05669378, -0.0600563 ,  0.04074132],
       [ 0.59172662, -0.46942446, -0.58273381,  0.42266187],
       [-0.26736003,  0.20073506,  0.2177041 , -0.11643728],
       [-0.04738818,  0.0276822 ,  0.13481389, -0.10838286]])

Simetrik Matris anlamındaki 'sym' parametresini kullandım ve bişeyler değişti.

In [22]:
linalg.solve(Matris,Birim_Matris,lower=True,assume_a="sym")

array([[ 0.15004933, -0.26583291,  0.02519933, -0.00941308],
       [-0.26583291,  0.56123837, -0.14167622,  0.07514466],
       [ 0.02519933, -0.14167622,  0.06127837,  0.0025066 ],
       [-0.00941308,  0.07514466,  0.0025066 , -0.01469294]])

In [23]:
linalg.solve(Matris,Birim_Matris,lower=True,assume_a="sym",transposed=True)

array([[ 0.15004933, -0.26583291,  0.02519933, -0.00941308],
       [-0.26583291,  0.56123837, -0.14167622,  0.07514466],
       [ 0.02519933, -0.14167622,  0.06127837,  0.0025066 ],
       [-0.00941308,  0.07514466,  0.0025066 , -0.01469294]])

Hermitian Matris anlamındaki 'her' parametresini kullandım ve yine bişeyler değişti.

In [24]:
linalg.solve(Matris,Birim_Matris,lower=True,assume_a="her")

array([[ 0.15004933, -0.26583291,  0.02519933, -0.00941308],
       [-0.26583291,  0.56123837, -0.14167622,  0.07514466],
       [ 0.02519933, -0.14167622,  0.06127837,  0.0025066 ],
       [-0.00941308,  0.07514466,  0.0025066 , -0.01469294]])

In [25]:
linalg.solve(Matris,Birim_Matris,lower=True,assume_a="her",transposed=True)

array([[ 0.15004933, -0.26583291,  0.02519933, -0.00941308],
       [-0.26583291,  0.56123837, -0.14167622,  0.07514466],
       [ 0.02519933, -0.14167622,  0.06127837,  0.0025066 ],
       [-0.00941308,  0.07514466,  0.0025066 , -0.01469294]])

Daha iyi anlamak için Matrislerin yerlerini değiştitip denedim.

In [26]:
linalg.solve(Birim_Matris,Matris)

array([[23., 24., 12., 11.],
       [ 9.,  5., 15., 16.],
       [10.,  7., 27., 31.],
       [33., 21., 34., 24.]])

In [27]:
linalg.solve(Birim_Matris.dot(2),Matris)

array([[11.5, 12. ,  6. ,  5.5],
       [ 4.5,  2.5,  7.5,  8. ],
       [ 5. ,  3.5, 13.5, 15.5],
       [16.5, 10.5, 17. , 12. ]])

In [28]:
linalg.solve(Birim_Matris.dot(3),Matris)

array([[ 7.66666667,  8.        ,  4.        ,  3.66666667],
       [ 3.        ,  1.66666667,  5.        ,  5.33333333],
       [ 3.33333333,  2.33333333,  9.        , 10.33333333],
       [11.        ,  7.        , 11.33333333,  8.        ]])

In [29]:
linalg.solve(Birim_Matris,Matris,lower=True,assume_a="gen")

array([[23., 24., 12., 11.],
       [ 9.,  5., 15., 16.],
       [10.,  7., 27., 31.],
       [33., 21., 34., 24.]])

In [30]:
linalg.solve(Birim_Matris,Matris,lower=True,assume_a="sym")

array([[23., 24., 12., 11.],
       [ 9.,  5., 15., 16.],
       [10.,  7., 27., 31.],
       [33., 21., 34., 24.]])

In [31]:
linalg.solve(Birim_Matris,Matris,lower=True,assume_a="her")

array([[23., 24., 12., 11.],
       [ 9.,  5., 15., 16.],
       [10.,  7., 27., 31.],
       [33., 21., 34., 24.]])

In [32]:
linalg.solve(Birim_Matris.dot(2),Matris,lower=True,assume_a="gen")

array([[11.5, 12. ,  6. ,  5.5],
       [ 4.5,  2.5,  7.5,  8. ],
       [ 5. ,  3.5, 13.5, 15.5],
       [16.5, 10.5, 17. , 12. ]])

In [33]:
linalg.solve(Birim_Matris.dot(2),Matris,lower=True,assume_a="sym")

array([[11.5, 12. ,  6. ,  5.5],
       [ 4.5,  2.5,  7.5,  8. ],
       [ 5. ,  3.5, 13.5, 15.5],
       [16.5, 10.5, 17. , 12. ]])

In [34]:
linalg.solve(Birim_Matris.dot(2),Matris,lower=True,assume_a="her")

array([[11.5, 12. ,  6. ,  5.5],
       [ 4.5,  2.5,  7.5,  8. ],
       [ 5. ,  3.5, 13.5, 15.5],
       [16.5, 10.5, 17. , 12. ]])

Anlaşılan o ki matrislerin yerleri bu işlemlerde önemli rol oynuyor dikkat etmekte fayda var.
* Birim matris simetrix bir matris olduğu için neyle çarparsak çarpalım simetrik yapısını koruyor.

* Matris olarak bir matrisin hermisyen olması  H*=H şeklinde ifade edilir.

* Hermisyen matrislerin en önemli özelliği üniter bir değişimle köşegenleştirilebilir olmaları ve köşegen elemanların gerçel olmaları zorunluluğu yüzünden gerçel özdeğerlere sahip olmalarıdır.

* Başka bir matrisle denemek daha çok şey öğretebilir.


In [41]:
Matris_2=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,10]])
Matris_2

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]])

Bana zaten varsıyan assume_a'nın gen olduğunu söylen bir hata mesajı verdi.

In [42]:
linalg.solve(Matris_2,Matris,assume_a="gen")

C:\Users\suley\AppData\Local\Temp/ipykernel_12096/696114814.py:1: LinAlgWarning: Ill-conditioned matrix (rcond=7.77467e-20): result may not be accurate.
  linalg.solve(Matris_2,Matris,assume_a="gen")


array([[ 1.98158384e+16,  1.08086391e+16, -4.50359963e+15,
        -1.98158384e+16],
       [-1.22317766e+18, -1.47537924e+18, -5.04403158e+17,
        -3.53082211e+17],
       [ 2.38690780e+18,  2.91833256e+18,  1.02231712e+18,
         7.65611937e+17],
       [-1.18354598e+18, -1.45376196e+18, -5.13410358e+17,
        -3.92713888e+17]])

In [43]:
linalg.solve(Matris_2,Matris,assume_a="sym")

array([[  1. ,  -8. ,   7. ,  -3. ],
       [-15. , -21. ,  -9. , -10. ],
       [-22. , -12. ,   5. ,  22. ],
       [ 29.5,  27.5,   2. ,  -8. ]])

In [40]:
linalg.solve(Matris_2,Matris,assume_a="her")

array([[  1. ,  -8. ,   7. ,  -3. ],
       [-15. , -21. ,  -9. , -10. ],
       [-22. , -12. ,   5. ,  22. ],
       [ 29.5,  27.5,   2. ,  -8. ]])

Bu iki yöntem arasında fark göremedim.Devam edecek..